### ISSUE TITLE
모달을 토스트처럼 전역으로 관리

### ISSUE THREAD

**Issue by un0211** [Epilogue-1/kokkok#102]
### 리팩토링 설명

모달을 전역으로 관리해서 어디서든 쉽게 모달을 열고 닫을 수 있도록 합니다.
+) 모달의 정의를 페이지/컴포넌트 밖으로 빼서 페이지/컴포넌트 내 코드를 간결하게 합니다.

### 현재 문제점

현재는 모달이 필요한 곳마다 모달 컴포넌트와 관련 설정(isVisible)을 추가해서 사용하고 있습니다.
컴포넌트를 추가할 수 없는 유틸 함수 등에서 필요할 때마다 모달을 열기가 번거롭습니다.
그리고 모달 관련 코드 때문에 각 컴포넌트의 실질적인 내용을 담은 코드를 확인할 때 번거롭습니다.

### 개선 방안

- 전역 관리
  - 토스트처럼 모달을 전역으로 관리해서, 루트 레이아웃 아래 두고 어디서나 쉽게 열고 닫을 수 있게 훅을 만듭니다.
- 컴포넌트 분리
  - 각 모달을 컴포넌트로 분리해서 모달 관련된 코드가 모달을 열려는 곳에서 차지하는 비중을 줄입니다.

예시) https://github.com/Part3-Team15/taskify/tree/develop/src
민재님이랑 같이 했던 프로젝트에서 썼던 방식인데, 모달 관련해서
- 전역 상태: store/reducers/modalSlice.ts
- 모달 열고닫는 훅: hooks/useModal.ts
- 모달 컴포넌트: components/modal/*
- 컴포넌트 아닌 여기저기서 모달 사용하는 예시: https://github.com/Part3-Team15/taskify/blob/8c40e2a07c362cd1bdf7c8be0323e4fea71ac04d/src/hooks/useRedirect.ts#L4

### 확인사항

- [X] 이 변경이 기존 기능에 영향을 주지 않습니다

**Comment by CitrusSoda** [comment]
오 좋은 내용 공유 감사합니다!! 댓글을 안 달수 없었네요 👍👍👍😭

제가 이해한 것은 모달을 사용하는 쪽에서가 아니라 루트에서 두어 위 프로젝트 switch case처럼 모달 변수들을 주어 한 곳에서 껐다 킬 수 있게 하고(어짜피 모달은 최대 한개니) 모달을 맨위로 옮긴 다음 isVisible은 전역상태로 설정하는게 맞을까요?(마찬가지로 모달 상태는 하나의 모달만 제어하고 전역상태로 빼면 관리가 쉬우니..?)

> 컴포넌트를 추가할 수 없는 유틸 함수 등에서 필요할 때마다 모달을 열기가 번거롭습니다.

이 말 때문에 의도를 이해했었는데 redux 쓰신분 멋지시네요... 참고한 레퍼런스가 따로 있으실까여

**Comment by CitrusSoda** [comment]
아 @wjsdncl 님!! 상위 태그에 종속적인 모달이 혹시 있을까요?

**Comment by un0211** [comment]
> 제가 이해한 것은 모달을 사용하는 쪽에서가 아니라 루트에서 두어 위 프로젝트 switch case처럼 모달 변수들을 주어 한 곳에서 껐다 킬 수 있게 하고(어짜피 모달은 최대 한개니) 모달을 맨위로 옮긴 다음 isVisible은 전역상태로 설정하는게 맞을까요?(마찬가지로 모달 상태는 하나의 모달만 제어하고 전역상태로 빼면 관리가 쉬우니..?)

넵! 루트 레이아웃에 모달을 추가하고, type 줘서 열기 전에 내용만 바꾸고 띄우는 겁니다!
모달 만들때 어떤 블로그 글 참고해서 완전 비슷하게 만든건데 그 글 어디갔나 모르겠네요 ㅠㅠ 디코에 적어놨을 것 같은데, 코드잇 디코가 사라져서.. 찾으면 알려드릴게요!

**Comment by wjsdncl** [comment]
> 아 @wjsdncl 님!! 상위 태그에 종속적인 모달이 혹시 있을까요?

아마 없는 걸로 압니다

--- 

전역으로 관리하는거 완전 동의합니다 점점 사용하다보니까 불편하더라고요
처음부터 전역으로 만들걸 그랬네요

**Comment by un0211** [comment]
[모달 참고자료](https://velog.io/@woohobi/Redux-toolkit%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%9C-%ED%9A%A8%EC%9C%A8%EC%A0%81%EC%9D%B8-%EB%AA%A8%EB%8B%AC%EC%B0%BD-%EA%B4%80%EB%A6%AC)
이거였던 것 같아요! 대충 이런 느낌이었어요

**Comment by heony704** [comment]
모달 사용할 때마다 isVisible 만들 필요없이 전역적으로 사용하는 거 너무 좋습니다! 👍👍👍
사용하기도 편해지고 관리하기도 좋아질 것 같아요.

그런데 제가 만든 한번만 쓰이는 캘린더 모달도 type으로 들어가게 되나요??

**Comment by un0211** [comment]
네, 말씀드린 방식 그대로 하면 모달은 하나고 type에 따라서 원하는 내용 채워주기 때문에 모든 모달이 type 가져야 합니다!
[Modal/index.tsx](https://github.com/Part3-Team15/taskify/pull/97/files#diff-0d59f88f197d374b4537b2b3fbc9660976ddcc32300c99fd3215c2fe5f5fd91a) 저희는 그냥 기본 디자인 모달들도 안에 들어갈 텍스트 직접 입력 안하고 타입을 줘서 정해놓은 상수값을 썼습니다. 생김새 따라 타입 줘도 되고, 이렇게 해도 될 것 같습니다.
