### ISSUE TITLE
Carousel의 중복 key 문제

### ISSUE THREAD

**Issue by heony704** [Epilogue-1/kokkok#109]
### 버그 설명

홈 화면의 PostIem의 Carousel은 사진 리스트에는 `carousel-image-${image}`, 하단의 dot 리스트에는 `carousel-dot-${image}`로 key 값이 부여되어 있습니다.
image 값이 동일한 경우 (동일한 사진의 경우) key 값이 중복되어 에러가 발생합니다.

### 재현 방법

1. 중복된 사진으로 게시글 올리기
2. 홈 화면 진입

### 기대한 결과

`carousel-image-${index}-${image}` 이런 식으로 index도 끼워넣으면 괜찮더라구요.
`carousel-dot-${image}-${index}` 이렇게 index를 뒤에 넣으면 index를 key로 쓰지마라 뭐라고 잔소리할 수도 있어서 중간에 넣는 걸 추천해요.

### 확인사항

- [X] 이미 존재하는 이슈인지 확인했습니다
- [X] 최신 버전에서도 발생하는 문제입니다

**Comment by wjsdncl** [comment]
# 감사합니다 수정하겠습니다! 🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️
