### ISSUE TITLE
비밀번호 변경 관련 건의사항

### ISSUE THREAD

**Issue by un0211** [Epilogue-1/kokkok#112]
### 관련 문제

지금은 로그인 된 상태에서 계정설정 -> 비밀번호 변경과, 로그인 안 된 상태에서 비밀번호 찾기로 접근 가능합니다.

1. 비밀번호 변경에서도 이메일 인증이 필요한가?
보통은 로그인 된 상태에서 비밀번호 변경을 누르면 현재 비밀번호, 새 비밀번호, 확인 이렇게 입력하는데,
우리는 이메일 인증을 해야 비밀번호 변경 가능합니다.
이메일 인증이 필요하다고 생각해서 넣은 걸까요?!

2. 헤더 및 버튼(?)이름을 변경하는 게 어떨까?!
지금은 비밀번호 모르는 상태든 아는 상태든 setp1,2는 비밀번호 변경, setp3은 비밀번호 초기화입니다. 
알고 있는 상태에서 변경하는 것과, 몰라서 초기화하는 건 다르다고 생각합니다.

3. 비로그인 상태에서 비밀번호 찾기로 초기화하면 로그인 되는 게 의도한 것인가??
지금은 비밀번호 찾기로 비밀번호를 변경하면 바로 로그인 되어서 홈으로 이동합니다. 
보통은 비밀번호 변경하고 다시 로그인해야 로그인이 되었던 것 같습니다.
번거롭게 다시 로그인 하는 과정을 줄였다 라는 의도라면 괜찮은 것 같지만 갑자기 로그인 되는 게 어색해서 이야기했습니다.

4. 관련 버그
- 비밀번호 찾기에서 이메일 인증은 로딩중 비활성화가 안됩니다.
- 비밀번호 찾기 이메일은 성공하거나 뒤로가기 하고 와도 내용이 유지됩니다. (전역상태 관리)

### 제안하는 해결책

1. 로그인 상태: 비밀번호 변경 페이지를 새로 만든다.
- 헤더: 비밀번호 변경으로 통일
- 내용: 현재 비밀번호, 새 비밀번호, 새 비밀번호 확인

2. 비로그인 상태: 비밀번호 초기화 페이지를 변경한다.
- 헤더: 비밀번호 초기화로 통일

3. 비밀번호 초기화시 바로 로그인 되는 건 논의하고 결정해서 유지 or 수정 (로그인 페이지로)

4. 관련 버그
- [ ] 비밀번호 찾기에서도 이메일 발송 처리 중 비활성화 
- [ ] 비밀번호 찾기도 전역상태 관리 해서 필요할 때 내용 비우기

### 대안

1, 2 관련해서 필요성이 없다고 느껴지거나, 새로 페이지 만드는 노력 대비 효용이 없다고 생각하면 그대로 두어도 괜찮을 것 같습니다. 그렇지만 그 경우 헤더는 다 비밀번호 변경이나 초기화 중 하나로 통일해도 좋을 것 같습니다.

### 확인사항

- [X] 이미 제안된 기능인지 확인했습니다
- [X] 이 기능이 프로젝트의 목적과 부합합니다

**Comment by YehaYoo** [comment]
### 1. 비밀번호 변경에서도 이메일 인증이 필요한가?
- 왜 이메일 인증을 하도록 기획했는가?
  -> 기획 부족입니다!!🥹👍 비밀번호를 찾기 위해 비밀번호 인증 페이지를 만들었을 때, 비밀번호 재설정도 우선 같은 페이지를 활용하자는 생각이었습니다!

#### -> 비밀번호 변경 페이지를 따로 만드는 방향으로 가겠습니다!

**Comment by YehaYoo** [comment]
### 3. 비로그인 상태에서 비밀번호 찾기로 초기화하면 로그인 되는 게 의도한 것인가?

의도한 부분입니다!

로그인 시도 -> 로그인 실패 -> 비밀번호 찾기 (이메일 입력 -  인증 코드 입력 - 비밀번호 재설정)
이러한 흐름을 생각해보면, 로그인을 하기 위해 여러 과정을 거친 사용자에게 자동 로그인이 긍정적인 경험으로 느껴질 것이라고 생각했습니다!
특히 모바일의 특성 중 다음과 같은 것들을 고려했습니다.
1. 작은 화면 크기와 입력의 어려움
- 복잡한 비밀번호(특수문자 포함)를 입력해야 하는 경우, 키보드 레이아웃을 자주 변경해야 함.

2. 환경적 불편함
모바일은 이동 중이나 한 손으로 사용하는 경우가 많아 키보드 조작이 어렵고, 주의가 분산될 가능성이 높음.

보안을 생각했을 때는, 새로운 비밀번호로 로그인되었다는 안내 메일 발송과 함께 사용자가 의도하지 않았다면 계정을 잠글 수 있게 하는 것을 생각해볼 수 있을 것 같습니다! 이 경우는 자동 로그인보다는 다시 비밀번호를 입력해 로그인하도록 하는 것이 더 좋겠네요!!

**Comment by un0211** [comment]
어차피 로그인 하려다가 비밀번호를 찾는 거라 바로 로그인 되는게 편할 것 같긴 한데, 이런 경험을 해 본 적 없어서 여쭤봤습니다!
의도하신 거라면 그대로 해봐도 괜찮을 것 같네요

**Comment by YehaYoo** [comment]
추가적으로 간편 로그인 계정으로 가입했을 때는 
계정 설정페이지에서 비밀번호 변경을 눌렀을 때, 비밀번호 변경 페이지 진입을 막고 모달로 안내하는 건 어떨까요??
