### ISSUE TITLE
앨범 선택 시 비율 문제

### ISSUE THREAD

**Issue by CitrusSoda** [Epilogue-1/kokkok#113]
### 관련 문제

플릭이라는 어플로 운동을 인증하려고 하였으나 비율 문제로 인해 사각형 안으로 강제로 들어가야 했습니다..ㅠㅠ 

### 제안하는 해결책

가변비율로 바꾸거나 바꾸기 힘들다면 사진 전체로 하는게 좋을 것 같아요

### 확인사항

- [X] 이미 제안된 기능인지 확인했습니다
- [X] 이 기능이 프로젝트의 목적과 부합합니다

**Comment by un0211** [comment]
이건 저도 전에 생각했다가, 저희 앱이 어차피 정사각형 모양으로 보여줄거면 어쩔 수 없는 것 같아서 말았습니다!
만약 비율 변경 가능하다면, 서로 다른 비율의 사진이 한 게시글에 올라가도 괜찮게 할지
그렇다면 보여줄 때 그에 의해 아래에 있는 내용들이 움직이게 될지, 아니면 정사각형을 가로세로 중 큰 길이에 맞추고 여백을 넣을지 등 생각해봐야 할 것 같습니다.

**Comment by CitrusSoda** [comment]
> 이건 저도 전에 생각했다가, 저희 앱이 어차피 정사각형 모양으로 보여줄거면 어쩔 수 없는 것 같아서 말았습니다! 만약 비율 변경 가능하다면, 서로 다른 비율의 사진이 한 게시글에 올라가도 괜찮게 할지 그렇다면 보여줄 때 그에 의해 아래에 있는 내용들이 움직이게 될지, 아니면 정사각형을 가로세로 중 큰 길이에 맞추고 여백을 넣을지 등 생각해봐야 할 것 같습니다.
> 
> -> 보여줄 때 어떻게 할지 고민해봐야 할 것 같습니다

사진을 클릭하면 다 보여줘야되나 쉽지않네요..😭

**Comment by wjsdncl** [comment]
이게 원래는 1:1 비율이 아니였는데 개발하다가 게시글을 한눈에 보려면 1:1 비율이 좋을거 같아서 예하님께 말씀드리고 그렇게 제작했었습니다.

혜원님이 말씀해주신 것처럼 보여주는게 문제라서
이미지를 업로드할 때는 자르지 않고 게시글에서만 잘려보이게 해 이미지를 터치하거나 다른 동작을 통해서 사진 전체를 볼 수 있게 하거나
게시글의 세로 비율을 늘려서 더 길게 볼 수 있게 만들수 있을거 같아요 이 경우에 혜원님이 말씀해주신 것처럼 비율이 다른 이미지의 경우 어떻게 할지 생각해봐야할거 같네요

아마 개발에서는 큰 문제 없을거 같긴합니다만 디자인의 영역이라 예하님 의견을 들어보는게 좋을거 같아요. 🫡
