### ISSUE TITLE
세션 및 로그인한 유저 정보 관련 논의

### ISSUE THREAD

**Issue by un0211** [Epilogue-1/kokkok#122]
# 1. 현재 상황

## 1. 상황
- 사용자 인증에 필요한 부분
  - 모두 supabase에서 알아서 해줌 (헤더에 토큰 포함시키기, 서버에서 유효한 토큰인지 검증 등)
- 로컬에서 로그인한 사용자 정보
  - 정보를 불러올 때 id가 필요한 경우: api 내에서 매번 getSession 사용 (ex. getHistories)
  - 유저 정보가 필요한 경우: useFetchData로 getCurrentUser의 내용을 캐시해서 불러옴 (ex. 프로필 페이지)

## 2. 원인
- 아마 제가 유저 유효한지 확인을 매번 하는 게 좋다고 들었다 했기 때문?

# 2. 건의사항
## 1. 로그인한 유저의 정보를 저장하자
- 유저 유효한지 확인, 접근할 수 있는 데이터 제한 등은 subapase에서 해결해 줌
- 우리는 로그인한 유저의 정보 (id, 이메일, 소개글, 프로필이미지 등)만 필요로 하고, 이건 저장해 놓고 써도 문제 없을 것으로 생각함
- 전역 상태 관리로 세션 바뀔 때 적절히 반영하고(로그인 -> 저장, 로그아웃 -> 제거), 필요한 경우 전역 상태 사용해서 로드

## 2. 이유
- 매 요청마다 getSession에서 id를 불러오는 경우, 한 페이지에서 여러 요청이 있을 때 각 요청 사이에 세션이 바뀌면 정보가 어떻게 될 것인지 모르겠어서?
이런 일이 실제로 일어날 수 있는지 모르겠고, 일어나도 세션 바뀌면 캐시된 쿼리 다 날려버리도록 해서 문제가 없을 수는 있음
아래 추가에 적힌 코드에서 getCurrentUser나 getCurrentSession이 캐시된 유저 정보랑, 막 불러온 유저 정보가 다를 경우는??
- 저장해놓고 써도 될 것 같아서?
제가 매번 세션 정보 받아오자고 했던 것 같은데, 다시 생각해 보니 유저 정보 정도는 저장해두고 써도 될 것 같음.
어차피 DB 접근 정책 설정하면 권한 없는 데이터 불러오지 못할 것이고, 권한 때문에 정보를 못 불러오면 토큰과 저장된 유저 정보가 잘 맞지 않는다는 것이니 에러메시지 띄우고 로그아웃 상태로 만들어 다시 로그인하게 하면 될 듯함.

## 3. 추가
```
  // 로그인한 유저 정보 조회
  const { data: session } = useFetchData<Session>(["session"], getCurrentSession);

  // 유저의 친구 요청 정보 조회
  const { data: requests } = useFetchData<RequestResponse>(
    ["friendRequests", session?.user.id, OFFSET],
    () => getFriendRequests(session?.user.id || ""),
    !!session?.user,
  );

  ...

  // 친구 요청이 추가되면 쿼리 다시 패치하도록 정보 구독
  useEffect(() => {
    const requestChannel = supabase
      .channel("friendRequest")
      .on(
        "postgres_changes", { ..., filter: `to=eq.${session.user.id}` }, (payload) => { ... },
      )
      .subscribe();

    return () => {
      supabase.removeChannel(requestChannel);
    };
  }, [session, queryClient.invalidateQueries]);
```
app/(protected)/(tabs)/friend/request.tsx 에 원래 이런 코드가 있었는데, 
getFriendRequests에서 getHistories처럼 세션을 안에서 받게 옮기려고 하니, 아래에 있는 구독 코드에서도 id가 필요하고,
웬만하면 친구요청 조회할 때 쓰는 id랑 구독할 때 쓰는 아이디랑 서로 같은 게 좋을 것 같다고 생각함.
-> 전역으로 저장하거나, 지금 코드 그대로 두거나 (getCurrentSession -> getCurrentUser 변경정도?), getFriendRequests에서 자기가 쓴 id를 return하는 등의 방법이 있음. 세 번째가 제일 별로일 것이라 생각함.
```
filter: `to=eq.${session.user.id}`
```

# 3. 요약
session 정보 말고, user 정보를 세션 변화시마다 jotai로 적절히 관리해서 필요한 곳(1-1 상황에서 getHistories나 프로필 페이지 모두)에서 쓰는 것 어떨까요?
제가 코드에서 유저 id 불러오는 부분을 api쪽으로 옮기려다가 위와 같은 제안을 하게 되었는데, 
빼먹거나 틀린 부분이 있을 수 있으니 다른 분들도 읽어보시고 댓글 남겨주시면 좋을 것 같습니다.

# 4. 추가
아니면 지금 제 코드랑 유사한 방식으로도 id를 통일해 볼 수 있을 것 같습니다.
getSession은 밖에서 쓸 일 없을 것 같으니 export를 빼고, 필요한 페이지에서 각자 아래 코드로 유저 정보 얻고
`const { data: currentUser } = useFetchData<User>(["currentUser"], getCurrentUser);`
getHistories 같은 함수에서 currentUser.id를 userId 인자로 받으면 쿼리키만 통일해도 요청마다 같은 userId 쓸 수 있을 것 같긴 합니다.
세션 변화시에도 queryClient.clear대신 queryClient.removeQueries(["currentUser"]) 해서 유저랑 관련된 정보만 날리고, getPosts 같이 유저랑 관련 없는 캐시된 데이터는 살릴 수 있을 것 같습니다.

**Comment by CitrusSoda** [comment]
그렇다면 jotai를 쓰는 것 보다 getCurrentUser에 user의 id를 포함해서 return시키는 것은 어떤 문제점이 있을까요?

현재 상황이랑 추가 공유까지 정말 감사합니다.. 저희의 QA팀이자 CTO세요...👍👍👍

**Comment by un0211** [comment]
제 생각에는 세션 바뀔 때 캐시된 currentUser를 잘 지워주기만 하면 비슷할 것 같습니다!
우리가 저장하고 있냐 queryClient 가 저장하고 있냐가 다른?!

아마도 유저 정보를 저장할 것이나 (쿼리 캐시 or 전역 상태 관리) vs 매번 요청할 것이냐 중에서 결정하고
저장할 거라면 저 두 가지 중에 하나 정해서 통일하면 될 것 같습니다.

제가 놓친 부분이 있을 수 있어서 다른 분들도 확인해주시면 좋을 것 같습니다.

**Comment by CitrusSoda** [comment]
추가로 jotai에 유저정보를 넣으면 좋지 않다고 생각되는 이유는

1. 받아올때부터 supabase가 검증해서 받아오니 오히려 supabase의 함수를 이용해야하며 react query까지 있으니 캐싱하면 된다.
    1-1. 1의 문제점 : 쿼리이용해서 캐싱할려니깐 이전거까지 받아와서 캐싱을 죽여야함... => jotai를 이용해도 이전 데이터를 변경해야함 = 세션의 변경이므로 jotai처리를 또 해주어야함 + supabase는 세션이 바뀌면 동작이 예상과 달라지니 오류를 알려주긴 하지만 jotai는 알지도 못하고 넘어갈 확률이 매우 높음

2. react-query 장점이라고 생각되는데 "나 서버 처리 해요"를 직관적으로 알 수 있음(데이터 라이브러리이므로) + 한줄로 끝, 하지만 jotai를 쓰면 set으로 다 적용시켜줘야함
        
이라고 생각되는데 언제나 의견 환영입니다!!!!

**Comment by CitrusSoda** [comment]
> 제 생각에는 세션 바뀔 때 캐시된 currentUser를 잘 지워주기만 하면 비슷할 것 같습니다! 우리가 저장하고 있냐 queryClient 가 저장하고 있냐가 다른?!
> 
> 아마도 유저 정보를 저장할 것이나 (쿼리 캐시 or 전역 상태 관리) vs 매번 요청할 것이냐 중에서 결정하고 저장할 거라면 저 두 가지 중에 하나 정해서 통일하면 될 것 같습니다.
> 
> 제가 놓친 부분이 있을 수 있어서 다른 분들도 확인해주시면 좋을 것 같습니다.

아 이거는 전 쿼리 캐시가 맞는 것 같습니다!

**Comment by un0211** [comment]
> 받아올때부터 supabase가 검증해서 받아오니 오히려 supabase의 함수를 이용해야하며 react query까지 있으니 캐싱하면 된다.
1-1. 1의 문제점 : 쿼리이용해서 캐싱할려니깐 이전거까지 받아와서 캐싱을 죽여야함... => jotai를 이용해도 이전 데이터를 변경해야함 = 세션의 변경이므로 jotai처리를 또 해주어야함 + supabase는 세션이 바뀌면 동작이 예상과 달라지니 오류를 알려주긴 하지만 jotai는 알지도 못하고 넘어갈 확률이 매우 높음
react-query 장점이라고 생각되는데 "나 서버 처리 해요"를 직관적으로 알 수 있음(데이터 라이브러리이므로) + 한줄로 끝, 하지만 jotai를 쓰면 set으로 다 적용시켜줘야함

제가 말했던 jotai 이용하자는 것은,
useAuthSession에서 세션이 변경되었을 때, 변경된 세션 정보를 이용해 getCurrentUser로 유저 정보를 받아오고, 그 정보를 저장하자는 것이었습니다. 저는 그렇게 하면 tanstack qeury 사용하는 것과 다르게 추가로 문제가 될 부분은 없다고 생각합니다.
(준혁님이 쓴 글을 제가 이해 못 한 걸지도..? 어떤 정보를 저장하는 거고, 왜 추가적인 문제가 생기는 지 모르겠습니다.)
그치만 "굳이 jotai를 한 번 더 쓸 필요 없이 캐시해서 쓰면 된다"라고 생각한다면 괜히 한 단계 거치는 것 같긴 하네요..

**Comment by CitrusSoda** [comment]
> 제가 말했던 jotai 이용하자는 것은, useAuthSession에서 세션이 변경되었을 때, 변경된 세션 정보를 이용해 getCurrentUser로 유저 정보를 받아오고, 그 정보를 저장하자는 것이었습니다. 저는 그렇게 하면 tanstack qeury 사용하는 것과 다르게 추가로 문제가 될 부분은 없다고 생각합니다. (준혁님이 쓴 글을 제가 이해 못 한 걸지도..? 어떤 정보를 저장하는 거고, 왜 추가적인 문제가 생기는 지 모르겠습니다.) 그치만 "굳이 jotai를 한 번 더 쓸 필요 없이 캐시해서 쓰면 된다"라고 생각한다면 괜히 한 단계 거치는 것 같긴 하네요..

요건 getCurrentUser만 jotai사용하는 이유가 세션이 바뀌면 어떻게 될 지 모르니까로 이해했는데 이게 맞다면 jotai의 유저는 현재 유저의 정보를 담아야만 할텐데 세션이 바뀜 = 유저가 바뀜이므로 그 상태를 받아와야 맞다고 생각하고 이것도 알 수 없는 오류이므로 굳이 jotai에 정보 담지 않고 supabase함수 써버리면 예상과 다르다는걸 바로 파악할 수 있으므로(세션이 바뀌는구나) 함수를 써야하는게 맞다고 생각했습니다!

**Comment by CitrusSoda** [comment]
> > 아 이거는 전 쿼리 캐시가 맞는 것 같습니다!
> 
> 저는 이전에 유저 관련된 거 저장하지 말고 필요할 때 요청하자고 정했던 것 같고, 그래서 승헌님이 매번 요청하는 방식으로 짠 거라고 이해했습니다. (맞을까요?) 저도 그런 방식으로 고쳐보려다가 굳이 저장하지 않을 필요 없다고 생각되어서 저장하는 것은 어떻겠냐고 이슈로 만든 것입니다. 방법으로는 전역 상태 관리를 이용하자고 했다가 그냥 캐시해도 괜찮을 것 같아서 추가한 상황입니다.
> 
> -> 일단 저장할것인가 O / X -> 저장한다면 쿼리 / 전역상태관리 두가지 정해야하는데 준혁님은 O / 쿼리 의견이신거죠???

요거는 이해했구 정보는 굳이 요청시마다 불러올 필요가 없어도 되지 않을까가 제 의견 맞습니다!! (O/쿼리)

**Comment by un0211** [comment]
> 요건 getCurrentUser만 jotai사용하는 이유가 세션이 바뀌면 어떻게 될 지 모르니까로 이해했는데 이게 맞다면 jotai의 유저는 현재 유저의 정보를 담아야만 할텐데 세션이 바뀜 = 유저가 바뀜이므로 그 상태를 받아와야 맞다고 생각하고 이것도 알 수 없는 오류이므로 굳이 jotai에 정보 담지 않고 supabase함수 써버리면 예상과 다르다는걸 바로 파악할 수 있으므로(세션이 바뀌는구나) 함수를 써야하는게 맞다고 생각했습니다!

저장할 것인가 O / X 에서 X를 선택해 매번 받아온다면
저는  getFriendRequest 내에서 session으로 정보를 받아오는 것과, `const { data: currentUser } = useFetchData<User>(["currentUser"], getCurrentUser);` 여기서 받아오는 것 (캐시된 것) 이 다를 수 있지 않을까
혹은 getHistories 와 거기서 부르는 다른 함수에서 각각 받아온 세션이 다를 수 있지 않을까를 말한 거였습니다.
id를 받아오는 소스가 같아야 한다고 생각해서!

세션이 바뀔 때 jotai든 쿼리든 바로 변동하고 그 한 소스에서 id나 정보를 가져오면 문제가 되지 않는다고 저는 생각합니다.
매번 getSession 하면 서로 다를 수 있지만

**Comment by CitrusSoda** [comment]
> > 요건 getCurrentUser만 jotai사용하는 이유가 세션이 바뀌면 어떻게 될 지 모르니까로 이해했는데 이게 맞다면 jotai의 유저는 현재 유저의 정보를 담아야만 할텐데 세션이 바뀜 = 유저가 바뀜이므로 그 상태를 받아와야 맞다고 생각하고 이것도 알 수 없는 오류이므로 굳이 jotai에 정보 담지 않고 supabase함수 써버리면 예상과 다르다는걸 바로 파악할 수 있으므로(세션이 바뀌는구나) 함수를 써야하는게 맞다고 생각했습니다!
> 
> 저장할 것인가 O / X 에서 X를 선택해 매번 받아온다면 저는 getFriendRequest 내에서 session으로 정보를 받아오는 것과, `const { data: currentUser } = useFetchData<User>(["currentUser"], getCurrentUser);` 여기서 받아오는 것 (캐시된 것) 이 다를 수 있지 않을까 혹은 getHistories 와 거기서 부르는 다른 함수에서 각각 받아온 세션이 다를 수 있지 않을까를 말한 거였습니다. id를 받아오는 소스가 같아야 한다고 생각해서!
> 
> 세션이 바뀔 때 jotai든 쿼리든 바로 변동하고 그 한 소스에서 id나 정보를 가져오면 문제가 되지 않는다고 저는 생각합니다. 매번 getSession 하면 서로 다를 수 있지만

이해했습니다!!!

추가로 이거랑은 별개고 PR에도 올리긴 했었는데 로그아웃, 회원탈퇴말고 세션이 바뀐적이 있으셨을까요?

**Comment by un0211** [comment]
> 그래서 승헌님이 매번 요청하는 방식으로 짠 거라고 이해했습니다. (맞을까요?)

요건 승헌님한테 여쭤본 거긴 합니다!! 그냥 제가 생각하기에 그러신 거 아닐까 해서
@heony704 이렇게 명시하지 않아서 헷갈렸을 것 같습니다..

그리고 상황 설명은 준혁님 답변을 제가 제대로 이해한 게 맞는지 확인차 추가한 것이었습니다!

**Comment by un0211** [comment]
> 추가로 이거랑은 별개고 PR에도 올리긴 했었는데 로그아웃, 회원탈퇴말고 세션이 바뀐적이 있으셨을까요?
> 혹시 해보시면서 회원 탈퇴, 로그아웃 제외하고 세션이 바뀐 적이 있으셨을까요?? 자주 말씀하셔서 궁금했습니다!

우리가 의도해서 바꾸는 건 이것밖에 없죠! 근데 잘못 동작해서 바뀔 수 있으니 말한거였습니다.

**Comment by CitrusSoda** [comment]
> > 추가로 이거랑은 별개고 PR에도 올리긴 했었는데 로그아웃, 회원탈퇴말고 세션이 바뀐적이 있으셨을까요?
> > 혹시 해보시면서 회원 탈퇴, 로그아웃 제외하고 세션이 바뀐 적이 있으셨을까요?? 자주 말씀하셔서 궁금했습니다!
> 
> 우리가 의도해서 바꾸는 건 이것밖에 없죠! 근데 잘못 동작해서 바뀔 수 있으니 말한거였습니다.

상세한 케이스까지..감사합니다!! 👍👍👍

**Comment by heony704** [comment]
> 저는 이전에 유저 관련된 거 저장하지 말고 필요할 때 요청하자고 정했던 것 같고, 그래서 승헌님이 매번 요청하는 방식으로 짠 거라고 이해했습니다. (맞을까요?)

@un0211 
네 맞아요.
초반에 유저 정보를 어떻게 다룰 지에 대해 정할 때 제가 적극적으로 참여하진 않아서 정확한 내용은 모르는데요.
유저 관련된거 저장하지 말고 필요할 때 요청하자고 정했던 건 기억납니다.
유저 관련된 정보를 클라이언트에서 저장하기에 보안 문제가 있을 수도 있다는 의견도 기억나네요.
그리고 그 후에 제가 개발하려는 기능에서 유저 정보가 필요할 때, 그냥 유저 정보를 저장하면 안되냐고 물어봤었는데요.
캐시됐기 때문에 매번 요청이 일어나지 않는다였나.. 하여튼 어떤 말을 들었고 딱히 반대로 들 근거가 없어서 납득하고 현재 방식으로 구현했습니다.

제가 한 답변이 원하는 답변일지 모르겠네요 😅
혹시 제가 이해를 잘못한 부분이 있다면 말해주세요!

**Comment by heony704** [comment]
저는 유저 정보를 앱에 저장했으면 좋겠어요.

유저 정보는 변경될 일이 거의 없는데 요청해서 가져오는 게 어색해요.
보통 앱을 사용할 때 사용자가 바뀔 일은 일년에 한번 있을까 말까 하잖아요.

그래서 그런가 로컬에 저장하는 게 더 직관적으로 느껴지기도 합니다.

유저 정보 전부는 아니어도 자주 변경되지 않는 정보는 로컬에 저장했으면 좋겠습니다.

추가로 expo의 SecureStore를 사용하면 정보를 암호화하여 저장할 수 있다던데 어떤가요?

**Comment by un0211** [comment]
> 초반에 유저 정보를 어떻게 다룰 지에 대해 정할 때 제가 적극적으로 참여하진 않아서 정확한 내용은 모르는데요.
유저 관련된거 저장하지 말고 필요할 때 요청하자고 정했던 건 기억납니다.
유저 관련된 정보를 클라이언트에서 저장하기에 보안 문제가 있을 수도 있다는 의견도 기억나네요.
그리고 그 후에 제가 개발하려는 기능에서 유저 정보가 필요할 때, 그냥 유저 정보를 저장하면 안되냐고 물어봤었는데요.
캐시됐기 때문에 매번 요청이 일어나지 않는다였나.. 하여튼 어떤 말을 들었고 딱히 반대로 들 근거가 없어서 납득하고 현재 방식으로 구현했습니다.

저도 그런 흐름이었던 것 같습니다!
저는 유저 정보를 useFetchData로 캐시했었는데, 승헌님은 캐시 없이 getCurrentSession으로 가져오시더라구요
그래서 원래 취지(필요할 때 가져온다)에 맞게 저도 각각 getCurrentSession으로 가져오라다가, 저장해놓는 게 더 좋을  것 같다고 생각해서 이 이슈를 만들게 됐습니다!

**Comment by heony704** [comment]
> 저도 그런 흐름이었던 것 같습니다! 저는 유저 정보를 useFetchData로 캐시했었는데, 승헌님은 캐시 없이 getCurrentSession으로 가져오시더라구요 그래서 원래 취지(필요할 때 가져온다)에 맞게 저도 각각 getCurrentSession으로 가져오라다가, 저장해놓는 게 더 좋을 것 같다고 생각해서 이 이슈를 만들게 됐습니다!

아!!!! 이거 혹시 supabase 파일의 api 함수 얘기 맞으신가요?!

그거는 사실.. 제가 유저 정보 저장 방식에 대해 확실히 인지하고 있지 않은 상황에서 
앱 사용자는 당연히 한명이고 계속 그 사람이 요청 보낼건데, api 함수마다 유저 정보를 파라미터로 넘겨줘야 하는 게 마음에 안들어서 그렇게 했어요 😅

제 마음대로 한건 아니고 그 당시에는 그렇게 짜도 똑같을 줄 알았습니다...
저도 잊고 있다가 방금 코드 찾아봤어요

**Comment by heony704** [comment]
> 그거는 사실.. 제가 유저 정보 저장 방식에 대해 확실히 인지하고 있지 않은 상황에서 앱 사용자는 당연히 한명이고 계속 그 사람이 요청 보낼건데, api 함수마다 유저 정보를 파라미터로 넘겨줘야 하는 게 마음에 안들어서 그렇게 했어요 😅

이렇게만 말하니까 그냥 요청에 userId가 있는 게 이상하는 것처럼 보이네여.
자기 자신의 정보에 대한 요청인데, userId를 파라미터로 넘겨준다는 것이 좀 어색합니다.

보통 user/me 요청같이 자기 자신에 대한 요청을 보낼 때 자신의 id를 보내지 않고, authorization 헤더에 정보를 담아 보내잖아요.
api 함수 내부에서 자기 자신의 정보를 처리하는 게 맞지 않을까 싶어요.

**Comment by un0211** [comment]
> 아!!!! 이거 혹시 supabase 파일의 api 함수 얘기 맞으신가요?!

넵!! 

> 그거는 사실.. 제가 유저 정보 저장 방식에 대해 확실히 인지하고 있지 않은 상황에서
앱 사용자는 당연히 한명이고 계속 그 사람이 요청 보낼건데, api 함수마다 유저 정보를 파라미터로 넘겨줘야 하는 게 마음에 안들어서 그렇게 했어요 😅

지금보니까 저도 이런 생각이 들긴 하더라구요.. 그래서 history 관련 api들처럼 고치려다가,
페이지에서 쓰는 id랑 api에서 쓰는 id랑 소스가 달라서 값이 달라지면 어쩌나 하고 이 이슈를 꺼내게 됐습니다.

> 보통 user/me 요청같이 자기 자신에 대한 요청을 보낼 때 자신의 id를 보내지 않고, authorization 헤더에 정보를 담아 보내잖아요.
api 함수 내부에서 자기 자신의 정보를 처리하는 게 맞지 않을까 싶어요.

지금의 getHistory처럼 api 내에서 세션 불러오는 방식을 이야기하는 걸까요???

다시 생각해보니 캐시 없이 getCurrentSession 쓰는 걸로 통일해도 id가 다를 문제는 없을 것 같네요
(중간에 세션 바뀌는 일도 일어나지 않을 것 같고, 일어나더라도 저희가 세션 바뀌면 캐시된 거 다 초기화 시켜서 괜찮을 것 같습니다.)

-> 제 코드를 승헌님 현재 코드처럼 바꿔도 될 것 같고, (getCurrentSession() -> session.user.id)
user id 포함된 정보를 로컬스토리지에 저장했다가 그 id를 써도 괜찮을 것 같습니다! 

저 지금 잘 모르겠어서 이따 회의 때 이야기해보면 좋을 것 같아요 ㅠㅠ

**Comment by un0211** [comment]
supabase.auth.getUser 사용하기로 변경
secureStore에 user id와 created at 만 저장하고, 필요할 때 그 값 쓰기로 결정!
