### ISSUE TITLE
페이지 표시하는 친구 컴포넌트로 분리

### ISSUE THREAD

**Issue by heony704** [Epilogue-1/kokkok#131]
### 리팩토링 설명

이 현재 페이지를 표시해주는 친구를 컴포넌트로 만들어 재사용하고 싶어요.

![image](https://github.com/user-attachments/assets/1209649d-3dee-49ce-8d1e-ad51b95450d1)

### 현재 문제점

이 친구가 원래 홈의 게시글에서만 사용되었는데, 제가 온보딩 페이지에서도 사용하게 되면서 코드가 중복되었습니다.
동일하게 동작되어야 요소가 흩어지면서 코드가 중복되고 유지보수하기 힘들어졌습니다.

- 홈의 게시글
![image](https://github.com/user-attachments/assets/1209649d-3dee-49ce-8d1e-ad51b95450d1)

- 온보딩 페이지
![image](https://github.com/user-attachments/assets/c55004b8-baa2-4cd1-99e9-711823634272)

### 개선 방안

`Page Indicator`라는 컴포넌트로 만들어서 코드 중복도 줄이고 일관된 UI를 가지도록 하고 싶습니다.

애니메이션을 둘 중 하나로 통일하고 싶은데 뭐가 하는 게 좋을까요?
저는 아래쪽이 더 일반적이어서 더 나은거 같아요.

1.
https://github.com/user-attachments/assets/a83c7ca8-d762-4db2-a94e-3d7078f5a656

2.
https://github.com/user-attachments/assets/0313bbf1-4c1d-4741-87f9-ef2df31e2f54

### 확인사항

- [X] 이 변경이 기존 기능에 영향을 주지 않습니다

**Comment by wjsdncl** [comment]
저도 아래가 좋을거 같습니다. 이렇게 같이 보니까 아래가 훨씬 깔끔하고 부드럽게 움직이는거 같네요👍
