### ISSUE TITLE
세팅 페이지 문의하기 추가

### ISSUE THREAD

**Issue by CitrusSoda** [Epilogue-1/kokkok#144]
### 관련 문제

세팅 페이지 문의하기 링크가 비어있습니다

### 제안하는 해결책

세팅 페이지 문의하기 링크를 추가합니다

### 확인사항

- [X] 이미 제안된 기능인지 확인했습니다
- [X] 이 기능이 프로젝트의 목적과 부합합니다

**Comment by YehaYoo** [comment]
https://docs.google.com/forms/d/1DudsplM5pFTxeM_WKvGXa9db1F2QOlmSMvWmCClrtFA/edit

일단 급하게 만들었습니다!!
