### ISSUE TITLE
존재하는 게시물인데 삭제된 게시물이라고 표시되는 문제

### ISSUE THREAD

**Issue by heony704** [Epilogue-1/kokkok#151]
### 버그 설명

마이 페이지에서 게시글 선택 후 게시글로 이동되면, 분명 존재하는 게시글임에도 "게시글이 삭제되었어요"라는 모달이 뜹니다.

<img src="https://github.com/user-attachments/assets/4b16d435-27a6-4b8f-989f-ee79b4b0329b" width="200" />

위 스크린샷은 왜인지 모달이 위로 안 올라오는데 게시글 삭제를 나타내는 `PostNotFoundModal`이 맞습니다.

모달 확인 누르고 마이페이지로 나가졌다가 다시 게시글 진입하면 모달 더 안뜨더라구요.

```tsx
// post/[postId].tsx

useFocusEffect(
  useCallback(() => {
    if (!postError && post) return;
    openModal({ type: "POST_NOT_FOUND" });
  }, [postError, post]),
);
```

위 코드에서 발생하는 문제인데,  post가 아직 안불러와져서 undefined여서 모달이 뜹니다.

### 재현 방법

1. 앱 시작
2. 마이페이지로 이동
3. 게시글 선택
4. "게시글이 삭제되었어요." 라는 모달 표시 => 버그

### 기대한 결과

게시글이 삭제된 경우에만 해당 모달을 띄워줘야 함

### 발생한 브라우저

기타

### 확인사항

- [X] 이미 존재하는 이슈인지 확인했습니다
- [X] 최신 버전에서도 발생하는 문제입니다

**Comment by heony704** [comment]
바로 fix PR 올릴게요

**Comment by wjsdncl** [comment]
> 바로 fix PR 올릴게요

아이고 확인 하고 수정까지 해주시다니 감사합니다 🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️
