### ISSUE TITLE
게시글 업로드 중 사진 선택 시 앨범이 제한되는 문제 수정

### ISSUE THREAD

**Issue by wjsdncl** [Epilogue-1/kokkok#71]
### 리팩토링 설명

게시글 업로드 할 때 사용자가 선택 할 수 있는 앨범의 개수가 제한적이여서 원하는 사진을 찾기가 힘듬

### 현재 문제점

현재 사용중인 라이브러리 문제 혹은 빌드 후 확인하면 해결될 수 있는 문제 일거 같습니다.

### 개선 방안

1. 라이브러리 변경
2. 빌드 후 확인

### 확인사항

- [X] 이 변경이 기존 기능에 영향을 주지 않습니다

**Comment by CitrusSoda** [comment]
퍼가요~
