### ISSUE TITLE
post 삭제 모달 동작 오류

### ISSUE THREAD

**Issue by CitrusSoda** [Epilogue-1/kokkok#77]
### 버그 설명

PostItem의 삭제 모달이 제대로 동작하지 않는 오류가 있습니다.

### 재현 방법

1. 삭제를 위해 미트볼 누르고 삭제 클릭
2. 무반응

### 기대한 결과

삭제 모달 열리기

생각한 해결 방법 : 아마 postItem은 여러개이기 때문에 isModal류 state가 동작 되면 재렌더링을 하고 post쪽도 재렌더링을 하게 될텐데 다시 PostItem을 불러 기본 값인 false로 인식하게 되어 모달이 제대로 동작하지 않는 것 같습니다.
따라서 모달을 PostItem 안쪽이 아닌 사용하는 쪽으로 빼야할 것 같습니다. (사용하는 mutation도 밖으로 빼내야해서 고려할 사항이 몇 있을 것 같습니다.)

### 확인사항

- [X] 이미 존재하는 이슈인지 확인했습니다
- [X] 최신 버전에서도 발생하는 문제입니다

**Comment by wjsdncl** [comment]
확인 감사합니다! 수정해보겠습니다🫡
