### ISSUE TITLE
알림 온 게시물이 삭제된 경우 반응 없음

### ISSUE THREAD

**Issue by un0211** [Epilogue-1/kokkok#82]
### 버그 설명

현재 좋아요/댓글 등 게시물 관련 알림을 누르면 해당 게시물로 이동하게 해 두었는데, 해당 게시물이 삭제된 경우 아무 일이 일어나지 않습니다.

### 재현 방법

삭제된 게시물 관련 알림 클릭

### 기대한 결과

1. 아래와 같은 코드 추가해서 게시물이 삭제되었다고 알려주면 좋을 것 같습니다. 현재는 alert인데 modal도 괜찮을 것 같습니다.
<img width="654" alt="image" src="https://github.com/user-attachments/assets/4c798f97-5015-4101-b5b1-78efb52a5cf0" />

2. 또는 게시글을 삭제할 때 관련 알림도 같이 삭제하도록 해야합니다. 그러면 아예 관련 알람이 뜨지 않습니다.
이 경우 DB에서 지금처럼 data로 값을 받는 게 아니라 postId, commentId를 이용해 relation을 거는 게 좋을 것 같습니다.

### 확인사항

- [X] 이미 존재하는 이슈인지 확인했습니다
- [X] 최신 버전에서도 발생하는 문제입니다

**Comment by un0211** [comment]
@YehaYoo 누군가 내가 작성했던 글이나 댓글에 주었던 피드백(알림)을 해당 글 삭제할때 같이 삭제하는 게 나을까요?!
알림이 남아있는 게 나을지, 사라지는 게 나을지?!

**Comment by YehaYoo** [comment]
@un0211 확인이 늦었습니다ㅜㅜ

**내가 삭제한 글에 대한 알림을 어떻게 할 것인가?**

**제안** 
좋아요는 삭제하고 댓글은 모달이 뜨게 하는 건 어떤가요? 구현하기에 괜찮을까요??
사용자의 특성, 현재 댓글의 기능을 생각하면 알림이 남아있으면 편리할 것 같습니다!


**이유**
- 가정된 상황 : 게시글을 삭제했는데, 방금 전 누가 댓글을 달았음 
- 사용자 특성 : 커뮤니케이션하는 것을 좋아함. 
- 댓글의 기능 : 좋아요보다 더 친교적인 커뮤니케이션 수단
- 결론 : 댓글을 확인하지 못했을 때, 작성자에게 어떤 내용의 댓글이 달렸다는 것을 확인할 수단을 제공해야함

**좋아요는 제외한 이유**
상황 : 좋아요 알림을 확인했는데 계속 삭제된 게시글
의견 : 알림 클릭의 목적은 누가 어떤 글에 좋아요를 눌렀는지 확인하는 것입니다. 게시글이 삭제된다면 어떤 글에 좋아요를 눌렀는지 확인할 수 없습니다. 목적을 이루지 못하는 경우가 연속되거나 누적되면 이또한 불편한 경험으로 느껴질 수 있다고 생각합니다! 그래서 필요성이 두드러지는 댓글만 제안드리게 되었습니다!!

**Comment by wjsdncl** [comment]
확인 감사합니다! 그러면 삭제된 게시글 이라면 모달로 알림 띄워 주겠습니다 🫡🫡
